package com.transaction.transaction_monitoring.service;

import com.transaction.transaction_monitoring.dto.TransactionRequest;
import com.transaction.transaction_monitoring.dto.TransactionResponse;
import com.transaction.transaction_monitoring.enums.AlertStatus;
import com.transaction.transaction_monitoring.enums.TransactionStatus;
import com.transaction.transaction_monitoring.enums.TransactionType;
import com.transaction.transaction_monitoring.exception.ResourceNotFoundException;
import com.transaction.transaction_monitoring.model.Alert;
import com.transaction.transaction_monitoring.model.AlertStatusHistory;
import com.transaction.transaction_monitoring.model.Transaction;
import com.transaction.transaction_monitoring.repository.AlertRepository;
import com.transaction.transaction_monitoring.repository.TransactionRepository;
import com.transaction.transaction_monitoring.rules.AlertCandidate;
import com.transaction.transaction_monitoring.rules.RuleEngineService;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

@Service
public class TransactionService {

    private final TransactionRepository transactionRepository;
    private final AlertRepository alertRepository;
    private final RuleEngineService ruleEngineService;

    public TransactionService(TransactionRepository transactionRepository,
                              AlertRepository alertRepository,
                              RuleEngineService ruleEngineService) {
        this.transactionRepository = transactionRepository;
        this.alertRepository = alertRepository;
        this.ruleEngineService = ruleEngineService;
    }

    public TransactionResponse create(TransactionRequest req) {
        Transaction tx = new Transaction();
        tx.setAccountId(req.getAccountId());
        tx.setPayeeId(req.getPayeeId());
        tx.setAmount(req.getAmount());
        tx.setType(req.getType() != null ? req.getType() : TransactionType.DEBIT);
        tx.setStatus(req.getStatus() != null ? req.getStatus() : TransactionStatus.COMPLETED);
        tx.setDescription(req.getDescription());
        tx.setTimestamp(req.getTimestamp() != null ? req.getTimestamp() : LocalDateTime.now());

        transactionRepository.save(tx);

        List<AlertCandidate> candidates = ruleEngineService.evaluate(tx);
        List<Long> alertIds = new ArrayList<>();

        for (AlertCandidate candidate : candidates) {
            if (alertRepository.existsOpenAlertForRule(candidate.getRuleId(), tx.getAccountId())) continue;

            Alert alert = new Alert();
            alert.setRuleId(candidate.getRuleId());
            alert.setSeverity(candidate.getSeverity());
            alert.setStatus(AlertStatus.OPEN);
            alert.setDescription(candidate.getDescription());
            alertRepository.save(alert);

            for (Long txId : candidate.getTriggeringTransactionIds()) {
                alertRepository.saveAlertTransaction(alert.getId(), txId);
            }

            AlertStatusHistory history = new AlertStatusHistory();
            history.setAlertId(alert.getId());
            history.setPreviousStatus(null);
            history.setNewStatus(AlertStatus.OPEN.name());
            history.setNotes("Alert auto-generated by rule: " + candidate.getRuleName());
            alertRepository.saveStatusHistory(history);

            alertIds.add(alert.getId());
        }

        return toResponse(tx, alertIds);
    }

    public List<TransactionResponse> findAll(String accountId, LocalDateTime from, LocalDateTime to,
                                             BigDecimal minAmount, BigDecimal maxAmount, String search) {
        return transactionRepository.findAll(accountId, from, to, minAmount, maxAmount, search)
                .stream().map(t -> toResponse(t, List.of())).toList();
    }

    public TransactionResponse findById(Long id) {
        Transaction tx = transactionRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Transaction not found: " + id));
        return toResponse(tx, List.of());
    }

    public List<TransactionResponse> generate(int count) {
        String[] accounts = {"ACC-001", "ACC-002", "ACC-003", "ACC-004", "ACC-005"};
        String[] payees = {"PAYEE-A", "PAYEE-B", "PAYEE-C", "PAYEE-D", "PAYEE-E", "PAYEE-NEW-1", "PAYEE-NEW-2", "ORG-12345"};
        Random rnd = new Random();
        List<TransactionResponse> results = new ArrayList<>();

        for (int i = 0; i < count; i++) {
            TransactionRequest req = new TransactionRequest();
            req.setAccountId(accounts[rnd.nextInt(accounts.length)]);
            req.setPayeeId(payees[rnd.nextInt(payees.length)]);
            req.setAmount(BigDecimal.valueOf(100 + rnd.nextInt(20000)));
            req.setType(rnd.nextBoolean() ? TransactionType.DEBIT : TransactionType.CREDIT);
            req.setStatus(TransactionStatus.COMPLETED);
            req.setDescription("Auto-generated transaction #" + (i + 1));
            results.add(create(req));
        }
        return results;
    }

    private TransactionResponse toResponse(Transaction tx, List<Long> alertIds) {
        TransactionResponse r = new TransactionResponse();
        r.setId(tx.getId());
        r.setAccountId(tx.getAccountId());
        r.setPayeeId(tx.getPayeeId());
        r.setAmount(tx.getAmount());
        r.setType(tx.getType());
        r.setStatus(tx.getStatus());
        r.setDescription(tx.getDescription());
        r.setTimestamp(tx.getTimestamp());
        r.setAlertIds(alertIds);
        return r;
    }
}
